### ISSUE TITLE
音频源音量超级大的时候 NPE

### ISSUE THREAD

**Issue by gordonpro** [GavinCT/AndroidMP3Recorder#10]
private void calculateRealVolume(short[] buffer, int readSize) 

这个方法里面
`double amplitude = sum / readSize;`

当声音很大的时候(对着麦克风敲)，导致 amplitude 是负值。
`mVolume = (int) Math.sqrt(amplitude);`

导致NPE。

**Comment by GavinCT** [comment]
请使用1.0.2版，谢谢反馈
