### ISSUE TITLE
和actionbarsherlock一起使用报错

### ISSUE THREAD

**Issue by chenchongyu** [GavinCT/AndroidMP3Recorder#14]
错误信息如下： java.lang.NoSuchFieldError: android.support.v4.app.Watson.mFragments
不知道是什么哪里冲突导致的？没人遇到过吗 ？
下面是整体的dependencies信息
compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
    compile 'com.czt.mp3recorder:library:1.0.2'
    compile 'com.android.support:support-v4:20.0.+'
    compile files('libs/fastjson-1.1.41.jar')
    compile files('libs/pinyin4j-2.5.0.jar')
    compile files('libs/xUtils-2.6.14.jar')

**Comment by GavinCT** [comment]
mp3 library 里  compile 'com.android.support:support-v4:23.1.1'  使用了高版本的support-v4  
详见 http://stackoverflow.com/questions/32078602/android-java-land-nosuchfielderror-after-update-to-sdk-23

**Comment by GavinCT** [comment]
https://github.com/GavinCT/AndroidMP3Recorder/releases  如果你没有后来版本的需求的话，可以使用1.0版 ，那个基于support-v4 21
