### ISSUE TITLE
AudioRecord.startRecord() 出现错误

### ISSUE THREAD

**Issue by ShieldShen** [GavinCT/AndroidMP3Recorder#15]
03-09 20:58:56.659 W/IMediaDeathNotifier: media server died
03-09 20:58:56.659 W/CameraBase: Camera service died!
03-09 20:58:56.661 E/MediaPlayer: error (100, 0)
03-09 20:58:56.661 W/AudioSystem: AudioFlinger server died!
03-09 20:58:56.661 E/MediaMetadataRetriever: failed to create IMediaMetadataRetriever object from server
03-09 20:58:56.661 W/AudioSystem: AudioPolicyService server died!
03-09 20:58:56.662 W/MediaMetadataRetriever: MediaMetadataRetriever server died!
03-09 20:58:56.667 I/ServiceManager: Waiting for service media.audio_flinger...
03-09 20:58:56.691 E/MediaPlayer: Error (100,0)

在我调用AudioRecord.startRecord()时会出现这样的错误，然后录音出来的文件就是104B大小。
我检查了已经正确stop以及release了，但是依然会出现这样的问题

**Comment by GavinCT** [comment]
是使用录音库的时候出现的？？
