### ISSUE TITLE
连续录制出现的文件损坏问题？这个问题很严重，如何解决？

### ISSUE THREAD

**Issue by PigFlyy** [GavinCT/AndroidMP3Recorder#22]

**Comment by PigFlyy** [comment]
希望作者可以及时修复这个问题，由于时间问题，现找到一种临时解决方案，可以解决文件损坏问题，希望可以帮助后来者。项目时间紧，原理等以后有时间再去研究~

问题再现：
如果将MP3Recorder让其做临时变量，如放入点击事件中，，则录制的音频多次录制后就会损坏。

解决方案：不要将MP3Recorder作为临时变量，你可以设置为私有的，先初始化，点击时间中直接调用，就不会出现损坏问题。
缺点：不方便，需要生成多个对象。

暂时是这样解决的，如果大家有更好的解决方案，欢迎讨论。
示例代码（正确）：

 
public class MainActivity extends Activity {

    private MP3Recorder mRecorder =  new MP3Recorder(new File(Environment.getExternalStorageDirectory(),"test.mp3"));;
    private MP3Recorder mRecorder1 =  new MP3Recorder(new File(Environment.getExternalStorageDirectory(),"test1.mp3"));
    int i=0;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        Button startButton = (Button) findViewById(R.id.StartButton);
        startButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {

                if(i==0) {
                    try {
                        mRecorder.start();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }else {
                    try {
                        mRecorder1.start();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        Button stopButton = (Button) findViewById(R.id.StopButton);
        stopButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if(i==0)mRecorder.stop();
                else  mRecorder1.stop();
                i++;
            }
        });
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mRecorder.stop();
    }
}

**Comment by GavinCT** [comment]
问题再现：
如果将MP3Recorder让其做临时变量，如放入点击事件中，，则录制的音频多次录制后就会损坏

之前是否调用了上一个的stop？  
另： 为什么会有这种场景？  用户多次点击的情况下不该屏蔽掉start调用么？ 重新调用start就是重新录制啊
