### ISSUE TITLE
录音转MP3结束事件

### ISSUE THREAD

**Issue by Staray** [GavinCT/AndroidMP3Recorder#25]
我遇到一个问题：
调用了mp3recorder.stop()方法后，获取文件，然后上传，发现MP3文件还没转换完成，必须等待一个不确定的时间，所以问能不能添加一个MP3文件转换完成的接口。

**Comment by GavinCT** [comment]
个人精力原因，本库暂不更新维护了   相关功能可参见pr https://github.com/GavinCT/AndroidMP3Recorder/pull/9   改造下本库源码即可达成功能
