### ISSUE TITLE
libmp3lame.so缺失

### ISSUE THREAD

**Issue by oliguo** [GavinCT/AndroidMP3Recorder#4]
正常運行，發現無法錄製，看了log發現有個so庫缺失
Log:
No JNI_OnLoad found in /data/app-lib/com.czt.mp3recorder.sample-1/libmp3lame.so 0x41de5c98, skipping init

**Comment by GavinCT** [comment]
看下readme里面的常见问题声明。 应该能解决你的问题

**Comment by oliguo** [comment]
thanks
