### ISSUE TITLE
5.0Jni出错问题

### ISSUE THREAD

**Issue by merhong2012** [GavinCT/AndroidMP3Recorder#6]
5.0会出现以下错误

java.lang.UnsatisfiedLinkError: No implementation found for void com.czt.mp3recorder.util.LameUtil.init(int, int, int, int, int) (tried Java_com_czt_mp3recorder_util_LameUtil_init and Java_com_czt_mp3recorder_util_LameUtil_init__IIIII)

10-20 17:53:11.599 20795-20795/cn.navyblue.doctor E/AndroidRuntime:     at com.czt.mp3recorder.util.LameUtil.init(Native Method)
10-20 17:53:11.599 20795-20795/cn.navyblue.doctor E/AndroidRuntime:     at com.czt.mp3recorder.MP3Recorder.initAudioRecorder(MP3Recorder.java:155)
10-20 17:53:11.599 20795-20795/cn.navyblue.doctor E/AndroidRuntime:     at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:66)

**Comment by GavinCT** [comment]
不会啊 我5.0运行正常啊 你看下你的so包提供的对不对 。 见readme  常见问题声明 部分

**Comment by merhong2012** [comment]
我是直接gradle引入的。
抱歉，是我手机的问题，在其他手机上运行没问题，我的手机是红米Note2.
不过有一个奇怪的现象，我新建了一个Demo,同样直接gradle引入，在我手机上录音没问题。
然后运行自己的项目，录音又出现以上错误，然后再运行demo，竟然也出现以上错误...我崩溃了。。
