### ISSUE TITLE
在联想K50-T5上报错

### ISSUE THREAD

**Issue by xj999** [GavinCT/AndroidMP3Recorder#7]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.epweike.employer.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.epweike.employer.android-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmp3lame.so"

 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.epweike.employer.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.epweike.employer.android-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmp3lame.so"

看这提示一直出现arm64  我怀疑是不是不支持64位cpu的问题?

**Comment by GavinCT** [comment]
1.0.1支持64位so
